"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Request(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        IDENTIFY: Request.Type.ValueType = ...  # 0
        CONNECT: Request.Type.ValueType = ...  # 1
        STREAM_OPEN: Request.Type.ValueType = ...  # 2
        STREAM_HANDLER: Request.Type.ValueType = ...  # 3
        DHT: Request.Type.ValueType = ...  # 4
        LIST_PEERS: Request.Type.ValueType = ...  # 5
        CONNMANAGER: Request.Type.ValueType = ...  # 6
        DISCONNECT: Request.Type.ValueType = ...  # 7
        PUBSUB: Request.Type.ValueType = ...  # 8
        PEERSTORE: Request.Type.ValueType = ...  # 9
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    IDENTIFY: Request.Type.ValueType = ...  # 0
    CONNECT: Request.Type.ValueType = ...  # 1
    STREAM_OPEN: Request.Type.ValueType = ...  # 2
    STREAM_HANDLER: Request.Type.ValueType = ...  # 3
    DHT: Request.Type.ValueType = ...  # 4
    LIST_PEERS: Request.Type.ValueType = ...  # 5
    CONNMANAGER: Request.Type.ValueType = ...  # 6
    DISCONNECT: Request.Type.ValueType = ...  # 7
    PUBSUB: Request.Type.ValueType = ...  # 8
    PEERSTORE: Request.Type.ValueType = ...  # 9

    TYPE_FIELD_NUMBER: builtins.int
    CONNECT_FIELD_NUMBER: builtins.int
    STREAMOPEN_FIELD_NUMBER: builtins.int
    STREAMHANDLER_FIELD_NUMBER: builtins.int
    DHT_FIELD_NUMBER: builtins.int
    CONNMANAGER_FIELD_NUMBER: builtins.int
    DISCONNECT_FIELD_NUMBER: builtins.int
    PUBSUB_FIELD_NUMBER: builtins.int
    PEERSTORE_FIELD_NUMBER: builtins.int
    type: global___Request.Type.ValueType = ...
    @property
    def connect(self) -> global___ConnectRequest: ...
    @property
    def streamOpen(self) -> global___StreamOpenRequest: ...
    @property
    def streamHandler(self) -> global___StreamHandlerRequest: ...
    @property
    def dht(self) -> global___DHTRequest: ...
    @property
    def connManager(self) -> global___ConnManagerRequest: ...
    @property
    def disconnect(self) -> global___DisconnectRequest: ...
    @property
    def pubsub(self) -> global___PSRequest: ...
    @property
    def peerStore(self) -> global___PeerstoreRequest: ...
    def __init__(self,
        *,
        type : typing.Optional[global___Request.Type.ValueType] = ...,
        connect : typing.Optional[global___ConnectRequest] = ...,
        streamOpen : typing.Optional[global___StreamOpenRequest] = ...,
        streamHandler : typing.Optional[global___StreamHandlerRequest] = ...,
        dht : typing.Optional[global___DHTRequest] = ...,
        connManager : typing.Optional[global___ConnManagerRequest] = ...,
        disconnect : typing.Optional[global___DisconnectRequest] = ...,
        pubsub : typing.Optional[global___PSRequest] = ...,
        peerStore : typing.Optional[global___PeerstoreRequest] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["connManager",b"connManager","connect",b"connect","dht",b"dht","disconnect",b"disconnect","peerStore",b"peerStore","pubsub",b"pubsub","streamHandler",b"streamHandler","streamOpen",b"streamOpen","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["connManager",b"connManager","connect",b"connect","dht",b"dht","disconnect",b"disconnect","peerStore",b"peerStore","pubsub",b"pubsub","streamHandler",b"streamHandler","streamOpen",b"streamOpen","type",b"type"]) -> None: ...
global___Request = Request

class Response(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        OK: Response.Type.ValueType = ...  # 0
        ERROR: Response.Type.ValueType = ...  # 1
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    OK: Response.Type.ValueType = ...  # 0
    ERROR: Response.Type.ValueType = ...  # 1

    TYPE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    STREAMINFO_FIELD_NUMBER: builtins.int
    IDENTIFY_FIELD_NUMBER: builtins.int
    DHT_FIELD_NUMBER: builtins.int
    PEERS_FIELD_NUMBER: builtins.int
    PUBSUB_FIELD_NUMBER: builtins.int
    PEERSTORE_FIELD_NUMBER: builtins.int
    type: global___Response.Type.ValueType = ...
    @property
    def error(self) -> global___ErrorResponse: ...
    @property
    def streamInfo(self) -> global___StreamInfo: ...
    @property
    def identify(self) -> global___IdentifyResponse: ...
    @property
    def dht(self) -> global___DHTResponse: ...
    @property
    def peers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PeerInfo]: ...
    @property
    def pubsub(self) -> global___PSResponse: ...
    @property
    def peerStore(self) -> global___PeerstoreResponse: ...
    def __init__(self,
        *,
        type : typing.Optional[global___Response.Type.ValueType] = ...,
        error : typing.Optional[global___ErrorResponse] = ...,
        streamInfo : typing.Optional[global___StreamInfo] = ...,
        identify : typing.Optional[global___IdentifyResponse] = ...,
        dht : typing.Optional[global___DHTResponse] = ...,
        peers : typing.Optional[typing.Iterable[global___PeerInfo]] = ...,
        pubsub : typing.Optional[global___PSResponse] = ...,
        peerStore : typing.Optional[global___PeerstoreResponse] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dht",b"dht","error",b"error","identify",b"identify","peerStore",b"peerStore","pubsub",b"pubsub","streamInfo",b"streamInfo","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dht",b"dht","error",b"error","identify",b"identify","peerStore",b"peerStore","peers",b"peers","pubsub",b"pubsub","streamInfo",b"streamInfo","type",b"type"]) -> None: ...
global___Response = Response

class IdentifyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    ADDRS_FIELD_NUMBER: builtins.int
    id: builtins.bytes = ...
    @property
    def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(self,
        *,
        id : typing.Optional[builtins.bytes] = ...,
        addrs : typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["addrs",b"addrs","id",b"id"]) -> None: ...
global___IdentifyResponse = IdentifyResponse

class ConnectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PEER_FIELD_NUMBER: builtins.int
    ADDRS_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    peer: builtins.bytes = ...
    @property
    def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    timeout: builtins.int = ...
    def __init__(self,
        *,
        peer : typing.Optional[builtins.bytes] = ...,
        addrs : typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        timeout : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["peer",b"peer","timeout",b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["addrs",b"addrs","peer",b"peer","timeout",b"timeout"]) -> None: ...
global___ConnectRequest = ConnectRequest

class StreamOpenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PEER_FIELD_NUMBER: builtins.int
    PROTO_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    peer: builtins.bytes = ...
    @property
    def proto(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    timeout: builtins.int = ...
    def __init__(self,
        *,
        peer : typing.Optional[builtins.bytes] = ...,
        proto : typing.Optional[typing.Iterable[typing.Text]] = ...,
        timeout : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["peer",b"peer","timeout",b"timeout"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["peer",b"peer","proto",b"proto","timeout",b"timeout"]) -> None: ...
global___StreamOpenRequest = StreamOpenRequest

class StreamHandlerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ADDR_FIELD_NUMBER: builtins.int
    PROTO_FIELD_NUMBER: builtins.int
    addr: builtins.bytes = ...
    @property
    def proto(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        addr : typing.Optional[builtins.bytes] = ...,
        proto : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["addr",b"addr"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["addr",b"addr","proto",b"proto"]) -> None: ...
global___StreamHandlerRequest = StreamHandlerRequest

class ErrorResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MSG_FIELD_NUMBER: builtins.int
    msg: typing.Text = ...
    def __init__(self,
        *,
        msg : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["msg",b"msg"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["msg",b"msg"]) -> None: ...
global___ErrorResponse = ErrorResponse

class StreamInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PEER_FIELD_NUMBER: builtins.int
    ADDR_FIELD_NUMBER: builtins.int
    PROTO_FIELD_NUMBER: builtins.int
    peer: builtins.bytes = ...
    addr: builtins.bytes = ...
    proto: typing.Text = ...
    def __init__(self,
        *,
        peer : typing.Optional[builtins.bytes] = ...,
        addr : typing.Optional[builtins.bytes] = ...,
        proto : typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["addr",b"addr","peer",b"peer","proto",b"proto"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["addr",b"addr","peer",b"peer","proto",b"proto"]) -> None: ...
global___StreamInfo = StreamInfo

class DHTRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        FIND_PEER: DHTRequest.Type.ValueType = ...  # 0
        FIND_PEERS_CONNECTED_TO_PEER: DHTRequest.Type.ValueType = ...  # 1
        FIND_PROVIDERS: DHTRequest.Type.ValueType = ...  # 2
        GET_CLOSEST_PEERS: DHTRequest.Type.ValueType = ...  # 3
        GET_PUBLIC_KEY: DHTRequest.Type.ValueType = ...  # 4
        GET_VALUE: DHTRequest.Type.ValueType = ...  # 5
        SEARCH_VALUE: DHTRequest.Type.ValueType = ...  # 6
        PUT_VALUE: DHTRequest.Type.ValueType = ...  # 7
        PROVIDE: DHTRequest.Type.ValueType = ...  # 8
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    FIND_PEER: DHTRequest.Type.ValueType = ...  # 0
    FIND_PEERS_CONNECTED_TO_PEER: DHTRequest.Type.ValueType = ...  # 1
    FIND_PROVIDERS: DHTRequest.Type.ValueType = ...  # 2
    GET_CLOSEST_PEERS: DHTRequest.Type.ValueType = ...  # 3
    GET_PUBLIC_KEY: DHTRequest.Type.ValueType = ...  # 4
    GET_VALUE: DHTRequest.Type.ValueType = ...  # 5
    SEARCH_VALUE: DHTRequest.Type.ValueType = ...  # 6
    PUT_VALUE: DHTRequest.Type.ValueType = ...  # 7
    PROVIDE: DHTRequest.Type.ValueType = ...  # 8

    TYPE_FIELD_NUMBER: builtins.int
    PEER_FIELD_NUMBER: builtins.int
    CID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    type: global___DHTRequest.Type.ValueType = ...
    peer: builtins.bytes = ...
    cid: builtins.bytes = ...
    key: builtins.bytes = ...
    value: builtins.bytes = ...
    count: builtins.int = ...
    timeout: builtins.int = ...
    def __init__(self,
        *,
        type : typing.Optional[global___DHTRequest.Type.ValueType] = ...,
        peer : typing.Optional[builtins.bytes] = ...,
        cid : typing.Optional[builtins.bytes] = ...,
        key : typing.Optional[builtins.bytes] = ...,
        value : typing.Optional[builtins.bytes] = ...,
        count : typing.Optional[builtins.int] = ...,
        timeout : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cid",b"cid","count",b"count","key",b"key","peer",b"peer","timeout",b"timeout","type",b"type","value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cid",b"cid","count",b"count","key",b"key","peer",b"peer","timeout",b"timeout","type",b"type","value",b"value"]) -> None: ...
global___DHTRequest = DHTRequest

class DHTResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        BEGIN: DHTResponse.Type.ValueType = ...  # 0
        VALUE: DHTResponse.Type.ValueType = ...  # 1
        END: DHTResponse.Type.ValueType = ...  # 2
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    BEGIN: DHTResponse.Type.ValueType = ...  # 0
    VALUE: DHTResponse.Type.ValueType = ...  # 1
    END: DHTResponse.Type.ValueType = ...  # 2

    TYPE_FIELD_NUMBER: builtins.int
    PEER_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    type: global___DHTResponse.Type.ValueType = ...
    @property
    def peer(self) -> global___PeerInfo: ...
    value: builtins.bytes = ...
    def __init__(self,
        *,
        type : typing.Optional[global___DHTResponse.Type.ValueType] = ...,
        peer : typing.Optional[global___PeerInfo] = ...,
        value : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["peer",b"peer","type",b"type","value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["peer",b"peer","type",b"type","value",b"value"]) -> None: ...
global___DHTResponse = DHTResponse

class PeerInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    ADDRS_FIELD_NUMBER: builtins.int
    id: builtins.bytes = ...
    @property
    def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(self,
        *,
        id : typing.Optional[builtins.bytes] = ...,
        addrs : typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["addrs",b"addrs","id",b"id"]) -> None: ...
global___PeerInfo = PeerInfo

class ConnManagerRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        TAG_PEER: ConnManagerRequest.Type.ValueType = ...  # 0
        UNTAG_PEER: ConnManagerRequest.Type.ValueType = ...  # 1
        TRIM: ConnManagerRequest.Type.ValueType = ...  # 2
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    TAG_PEER: ConnManagerRequest.Type.ValueType = ...  # 0
    UNTAG_PEER: ConnManagerRequest.Type.ValueType = ...  # 1
    TRIM: ConnManagerRequest.Type.ValueType = ...  # 2

    TYPE_FIELD_NUMBER: builtins.int
    PEER_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    WEIGHT_FIELD_NUMBER: builtins.int
    type: global___ConnManagerRequest.Type.ValueType = ...
    peer: builtins.bytes = ...
    tag: typing.Text = ...
    weight: builtins.int = ...
    def __init__(self,
        *,
        type : typing.Optional[global___ConnManagerRequest.Type.ValueType] = ...,
        peer : typing.Optional[builtins.bytes] = ...,
        tag : typing.Optional[typing.Text] = ...,
        weight : typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["peer",b"peer","tag",b"tag","type",b"type","weight",b"weight"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["peer",b"peer","tag",b"tag","type",b"type","weight",b"weight"]) -> None: ...
global___ConnManagerRequest = ConnManagerRequest

class DisconnectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PEER_FIELD_NUMBER: builtins.int
    peer: builtins.bytes = ...
    def __init__(self,
        *,
        peer : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["peer",b"peer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["peer",b"peer"]) -> None: ...
global___DisconnectRequest = DisconnectRequest

class PSRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        GET_TOPICS: PSRequest.Type.ValueType = ...  # 0
        LIST_PEERS: PSRequest.Type.ValueType = ...  # 1
        PUBLISH: PSRequest.Type.ValueType = ...  # 2
        SUBSCRIBE: PSRequest.Type.ValueType = ...  # 3
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    GET_TOPICS: PSRequest.Type.ValueType = ...  # 0
    LIST_PEERS: PSRequest.Type.ValueType = ...  # 1
    PUBLISH: PSRequest.Type.ValueType = ...  # 2
    SUBSCRIBE: PSRequest.Type.ValueType = ...  # 3

    TYPE_FIELD_NUMBER: builtins.int
    TOPIC_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    type: global___PSRequest.Type.ValueType = ...
    topic: typing.Text = ...
    data: builtins.bytes = ...
    def __init__(self,
        *,
        type : typing.Optional[global___PSRequest.Type.ValueType] = ...,
        topic : typing.Optional[typing.Text] = ...,
        data : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","topic",b"topic","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","topic",b"topic","type",b"type"]) -> None: ...
global___PSRequest = PSRequest

class PSMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FROM_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    SEQNO_FIELD_NUMBER: builtins.int
    TOPICIDS_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    data: builtins.bytes = ...
    seqno: builtins.bytes = ...
    @property
    def topicIDs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    signature: builtins.bytes = ...
    key: builtins.bytes = ...
    def __init__(self,
        *,
        data : typing.Optional[builtins.bytes] = ...,
        seqno : typing.Optional[builtins.bytes] = ...,
        topicIDs : typing.Optional[typing.Iterable[typing.Text]] = ...,
        signature : typing.Optional[builtins.bytes] = ...,
        key : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","from",b"from","key",b"key","seqno",b"seqno","signature",b"signature"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","from",b"from","key",b"key","seqno",b"seqno","signature",b"signature","topicIDs",b"topicIDs"]) -> None: ...
global___PSMessage = PSMessage

class PSResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TOPICS_FIELD_NUMBER: builtins.int
    PEERIDS_FIELD_NUMBER: builtins.int
    @property
    def topics(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def peerIDs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(self,
        *,
        topics : typing.Optional[typing.Iterable[typing.Text]] = ...,
        peerIDs : typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["peerIDs",b"peerIDs","topics",b"topics"]) -> None: ...
global___PSResponse = PSResponse

class PeerstoreRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        GET_PROTOCOLS: PeerstoreRequest.Type.ValueType = ...  # 1
        GET_PEER_INFO: PeerstoreRequest.Type.ValueType = ...  # 2
    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        pass

    GET_PROTOCOLS: PeerstoreRequest.Type.ValueType = ...  # 1
    GET_PEER_INFO: PeerstoreRequest.Type.ValueType = ...  # 2

    TYPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    PROTOS_FIELD_NUMBER: builtins.int
    type: global___PeerstoreRequest.Type.ValueType = ...
    id: builtins.bytes = ...
    @property
    def protos(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        type : typing.Optional[global___PeerstoreRequest.Type.ValueType] = ...,
        id : typing.Optional[builtins.bytes] = ...,
        protos : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id",b"id","type",b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","protos",b"protos","type",b"type"]) -> None: ...
global___PeerstoreRequest = PeerstoreRequest

class PeerstoreResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PEER_FIELD_NUMBER: builtins.int
    PROTOS_FIELD_NUMBER: builtins.int
    @property
    def peer(self) -> global___PeerInfo: ...
    @property
    def protos(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        peer : typing.Optional[global___PeerInfo] = ...,
        protos : typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["peer",b"peer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["peer",b"peer","protos",b"protos"]) -> None: ...
global___PeerstoreResponse = PeerstoreResponse
